FRONTEND_URL: "http://localhost:3000"
# SMTP_ADDRESS: "smtp.gmail.com"
# SMTP_PORT: "587"
# SMTP_DOMAIN: "gmail.com"
# SMTP_USERNAME: "your_email@gmail.com"
# SMTP_PASSWORD: "your_app_password"
# SMTP_AUTHENTICATION: "plain"
# SMTP_ENABLE_STARTTLS: "true"
# MAILER_FROM: "noreply@aclcormoc.edu.ph"